version: '3.8'
services:
  app:
    image: all-countries
    build: .
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    env_file:
      - .env  
    command: ["go", "run", "/app/main.go"] 
    networks:
      - my-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
       - ../home/deploy/frontend/dist:/usr/share/nginx/html
       - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - grafana
    networks:
      - my-network

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:1.4.0
    ports:
      - "9113:9113"
    command:
      - "--nginx.scrape-uri=http://nginx/nginx_status"
    depends_on:
      - nginx
    networks:
      - my-network  

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - my-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - app
    networks:
      - my-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - my-network

volumes:
  postgres_data:
  redis_data:
  grafana_data:

networks:
  my-network:
    external: true
