version: '3.8'
services:
  app:
    image: all-countries
    build: .
    volumes:
      - ./:/app  # монтируем локальную папку ./app в контейнер в /app
    ports:
      - "8080:8080"
    env_file:
      - .env  
    command: ["go", "run", "/app/main.go"]  # Запуск приложения напрямую через go run

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: